### ISSUE TITLE
Bug String.formatURL

### ISSUE THREAD

**Issue by faizandedia** [windy1/google-places-api-java#11]
There is a bug when generating URL , you should pass the Locale.ENGLISH while formatting it otherwise it will generate the wrong url. In my case I am using arabic locale after debugging it, seems url is wrong.

//Current 

private static String buildUrl(String method, String params, Param... extraParams) {
        String url = String.format("%s%s/json?%s", API_URL, method, params);
        url = addExtraParams(url, extraParams);
        url = url.replace(' ', '+');
        return url;
    }

//Should be  Locale.ENGLISH

private static String buildUrl(String method, String params, Param... extraParams) {
        String url = String.format(Locale.ENGLISH,"%s%s/json?%s", API_URL, method, params);
        url = addExtraParams(url, extraParams);
        url = url.replace(' ', '+');
        return url;
    }

**Comment by windy1** [comment]
Thank you for pointing this out @faizandedia. This has been fixed in d1c2801391199352e3344563bccf9a530705b89f
