### ISSUE TITLE
API Key Is Checked In

### ISSUE THREAD

**Issue by jameskbride** [windy1/google-places-api-java#14]
Walker, I checked out your code, and when I built it locally I noticed your Places API key has been checked in.  I would remove that and either mock out the tests you currently have in place or require developers to insert their own API key before building.

**Comment by windy1** [comment]
Thank you for pointing this out James, the file has been added to the .gitignore (a0c621231f426971493f2b83edc4c9e44531f2b6) and removed from the commit history. Developers should create their own places_api.key file with their Google Places API key before trying to run tests on the project as it now says in the README.md (d650650dc97eae158fb9e1a61aadf7cce91d97a1).
