### ISSUE TITLE
Put this on Maven repo

### ISSUE THREAD

**Issue by AabidMulani** [windy1/google-places-api-java#2]

**Comment by pauloubuntu** [comment]
Hi @windy1,

I've ssen that we can already find google-places-api-java on Maven central but it has only the 1.2.4 version. Could you deploy the latest version(1.2.6) so far to Maven central ?

Regards

**Comment by windy1** [comment]
Yeah I've been having some issues with deployment to maven central so I've temporarily disabled it until I have the time to fix the issues.

**Comment by windy1** [comment]
In the mean time you can get the latests releases here: https://github.com/windy1/google-places-api-java/releases

**Comment by windy1** [comment]
Latest and greatest build is now available on maven central.

**Comment by pauloubuntu** [comment]
Awesome! :+1:
