### ISSUE TITLE
Execution Failed for task :app:dexDebug

### ISSUE THREAD

**Issue by davjr96** [windy1/google-places-api-java#22]
When I add the dependency 
    compile 'org.apache.httpcomponents:httpclient-android:4.3.5.1'
I get the following error
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_40\bin\java.exe'' finished with non-zero exit value 2

but if I take it out I get a runtime error from the library. Any suggestions?
Thanks!

**Comment by windy1** [comment]
This doesn't give me too much information but have you added

```java
repositories {
    mavenCentral()
}
`

to your gradle file?

**Comment by davjr96** [comment]
Sorry, what else can I provide that is helpful?
Yes I have, here's a copy of my gradle file
```javascript
    apply plugin: 'com.android.application'
    android {
    compileSdkVersion 21
    buildToolsVersion "22.0.0"
    defaultConfig {
        applicationId "com.test.myapp"
        minSdkVersion 20
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
    repositories {
    mavenCentral()
}
    dependencies {
        compile 'com.android.support:appcompat-v7:21.0.3'
        compile 'org.apache.httpcomponents:httpclient-android:4.3.5.1'
        compile files('libs/google-places-api-java.jar')
    }
```

**Comment by windy1** [comment]
Try replacing

```java
compile files('libs/google-places-api-java.jar')
```

with

```java
compile 'se.walkercrou:google-places-api-java:2.1.0'
```

**Comment by davjr96** [comment]
That appears to work! I was using the example in the readme and did not realize the versions were different. Thanks for the great support and library!

**Comment by windy1** [comment]
Hey, no problem @davjr96!
