### ISSUE TITLE
Issue with nearby search when setting language to french

### ISSUE THREAD

**Issue by gbero** [windy1/google-places-api-java#24]
Hi,

The request seems wrong when using the french language.

The latitude/longitude fields are changed : 

46.12345 --> 46,12345

I've created  a pull request to fix that.
https://github.com/windy1/google-places-api-java/pull/23

Cheers,

**Comment by gbero** [comment]
https://github.com/windy1/google-places-api-java/pull/23

**Comment by gbero** [comment]
Thanks @windy1,
Can you make a release with this ?

**Comment by windy1** [comment]
Done, `v2.1.2` should be available shortly.

**Comment by gbero** [comment]
Thanks a lot!

**Comment by windy1** [comment]
No prob @gbero!
