### ISSUE TITLE
REQUEST_DENIED: "This IP, site or mobile application is not authorized to use this API key."

### ISSUE THREAD

**Issue by TheLester** [windy1/google-places-api-java#25]
i have an exception like this  - REQUEST_DENIED: "This IP, site or mobile application is not authorized to use this API key."

**Comment by jameskbride** [comment]
Hi @TheLester, I just had this issue the other day, it is not actually an issue with this library.  

First, make sure you're using a server API key, not an Android/iOS key (if you're doing mobile development). See this stackoverflow post: http://stackoverflow.com/questions/14654758/google-places-api-request-denied-for-android-autocomplete-even-with-the-right-a . The TL;DR version of that link is that Google Places API doesn't support the Android/iOS key option, only the server option.  

Second, and this goes without saying, make sure you're passing the key to the GooglePlaces instance.  

Lastly, if you're restricting use of the API key by IP make sure your request is coming from an allowed address.

**Comment by TheLester** [comment]
THanks, i generated api key for android, instead of for browser one

**Comment by shainu3** [comment]
I faced the problem because i did not enable the APL key in Google console.
