### ISSUE TITLE
Detail query?

### ISSUE THREAD

**Issue by LoriGolden** [windy1/google-places-api-java#26]
I'm not seeing an Api for the Google Detail query - getPlacesByQuery is a text search and does not bring back address components.

**Comment by windy1** [comment]
https://github.com/windy1/google-places-api-java#place-details

**Comment by LoriGolden** [comment]
As mentioned above doing a text search which #place-details does cost 10x the amount of normal query AND it does not bring back details.

**Comment by windy1** [comment]
What exactly are you trying to do @LoriGolden?

**Comment by LoriGolden** [comment]
The primary function at the moment is to collect latitude/longitude data.  I'm also saving Google places data for later processing.    I found that autocomplete places seems to make the best matches to my data and details provides the lat/longitude information.     text searches cost 10x the amount of other searches.

**Comment by windy1** [comment]
You have to call `getDetails()` on each place object you get from `getPlacesByQuery`. I know it's more expensive but it's currently the only way possible with Google's web API.

**Comment by LoriGolden** [comment]
getDetails() does not call the Google details url but rather the text url.  The details url just charges for 1 although you need to have the the place id.

**Comment by windy1** [comment]
@LoriGolden No you're mistaken. [`place.getDetails()` calls `client.getPlaceById()`](https://github.com/windy1/google-places-api-java/blob/master/src/main/java/se/walkercrou/places/Place.java#L798) which then in turn [makes a request to the place details URL](https://github.com/windy1/google-places-api-java/blob/master/src/main/java/se/walkercrou/places/GooglePlaces.java#L256).

**Comment by lorigoldensmartfinance** [comment]
Thanks.

**Comment by NicolasBerger** [comment]
Hi, I'm currently trying to get the details of a list of Places in Paris. The first iteration works fine but the second get stuck on getDetails(), do I miss something ?
```java
		List<Place> places = client.getNearbyPlaces(48.927597, 2.263365, 10, GooglePlaces.MAXIMUM_RESULTS);
		for (Place place : places) {
			System.out.println("Name: " + place.getName());
			Place detail = place.getDetails();
			System.out.println("ID: " + detail.getPlaceId());
        }
```
