### ISSUE TITLE
SSLPeerUnverifiedException

### ISSUE THREAD

**Issue by Bachn1989** [windy1/google-places-api-java#27]
I get the following error
```
Exception in thread "main" se.walkercrou.places.exception.GooglePlacesException: java.io.IOException: javax.net.ssl.SSLPeerUnverifiedException: Host name 'maps.googleapis.com' does not match the certificate subject provided by the peer (CN=*.storage.googleapis.com, O=Google Inc, L=Mountain View, ST=California, C=US)
```

with the following invocation

```
GooglePlaces client = new GooglePlaces(googleApiKey);                   
List<Prediction> predictions = client.getPlacePredictions(location);
```

If I manually do a HTTPS connection, I encounter no problems. I'd appreciate any suggestions you have.

**Comment by windy1** [comment]
@Bachn1989 Are you working with Android? If so, could you provide your gradle file please?

**Comment by Bachn1989** [comment]
@windy1 I am not working with Android.

**Comment by windy1** [comment]
@Bachn1989 I've been unable to reproduce this, can you give me a little more information on what you are trying to do in what environment?

**Comment by mvaneggermond** [comment]
Just had the same issue; for me it was the result of a conflict with imports. Another Maven dependency (htmlunit) was pulling in Apache HTTP Client 4.4.x. Removing HTTP Client from the dependencies resolved the error.

**Comment by windy1** [comment]
Closing this now as it appears to be an issue external to this project.
