### ISSUE TITLE
Error log on calling GooglePlaces constructor with API key

### ISSUE THREAD

**Issue by rohandalvi** [windy1/google-places-api-java#28]
Error: https://gist.github.com/rohandalvi/3163b833f9f4840066e2

Link to code: https://gist.github.com/rohandalvi/cbe7de2cd3748c6a5a75

Project Gradle file: https://gist.github.com/rohandalvi/9e5fe0c7328f4329a103

App Gradle file: https://gist.github.com/044b0e636aa6a4f17eed

**Comment by windy1** [comment]
Hey @rohandalvi! Give this a shot: https://gist.github.com/windy1/89dc03f2a13d3b37d0cd

**Comment by rohandalvi** [comment]
Led to further errors while building: https://gist.github.com/rohandalvi/1794af8547fa7367abf8

**Comment by windy1** [comment]
It says how to fix it right in the error...

```
You can ignore those files in your build.gradle:
	android {
	  packagingOptions {
	    exclude 'LICENSE.txt'
	  }
	}
```
