### ISSUE TITLE
Cant find method to get location details from place id

### ISSUE THREAD

**Issue by AabidMulani** [windy1/google-places-api-java#4]
I get a list of suggestion from the AutoComplete api, but now i need to get the latlng for those suggestion. So how do I hit the api with the placeId

https://maps.googleapis.com/maps/api/place/details/json?placeid=ChIJN1t_tDeuEmsRUsoyG83frY4&key=

**Comment by windy1** [comment]
Please refer to https://github.com/windy1/google-places-api-java/blob/master/src/main/java/se/walkercrou/places/GooglePlacesInterface.java#L480
