### ISSUE TITLE
Latest version 2.1.7 is not available in maven.

### ISSUE THREAD

**Issue by liyaguang** [windy1/google-places-api-java#43]
Hi,
Can you upload the latest version to maven repository? The one in maven (version 2.1.2) has some issue #35 .

**Comment by windy1** [comment]
Sorry I've been really busy IRL. Maven has been acting fucky for me lately, I'll try and figure this out soon.

**Comment by windy1** [comment]
Deployed, should be available on maven central soon.

**Comment by blackleg** [comment]
Thanks
