### ISSUE TITLE
getNearbyPlaces(UNLIMITED_RESULTS)

### ISSUE THREAD

**Issue by NicolasBerger** [windy1/google-places-api-java#45]
Hello,

I am trying to get an "unlimited" amount of results out of the `getNearbyPlaces()` method, so I give `Integer.MAX_VALUE` as limit but I always get 60 results.

I went into the GooglePlaces class and it seems the `getPlaces()` method overrides my limit with :
```java
limit = Math.min(limit, MAXIMUM_RESULTS); // max of 60 results possible
```
But then the number of request that have to be sent is calculated with the new limit : 
```java
int pages = (int) Math.ceil(limit / (double) MAXIMUM_PAGE_RESULTS);
```

So obviously I can never have more than 60 results even though it should be possible.

**Comment by hamdikavak** [comment]
60 result is the limitation imposed by Google Places API, not this library. Please check https://developers.google.com/places/web-service/search#PlaceSearchResponses

**Comment by NicolasBerger** [comment]
So when the javadoc of the API says "Returns the places at the specified latitude and longitude within the specified radius. If the specified limit is greater than MAXIMUM_PAGE_RESULTS, multiple HTTP GET requests may be made if necessary."

I thought the API would handle the multiple calls

**Comment by hamdikavak** [comment]
That is actually what it does. You will see that MAXIMUM_PAGE_RESULTS=20. If necessary, the library makes additional calls up to 3 times in total to get up to 60 results. I hope this make sense.

**Comment by NicolasBerger** [comment]
It does make sense if the limit you provide is 60 or less.
But the way the javadoc is written, I understand that the API handles the case when you want more by making a loop over http GET and requesting everything up to the limit you want.
Isn't it possible ?

**Comment by hamdikavak** [comment]
Unfortunately, the problem is that the Places API will return 60 places even if your radius covers 1000 places. 

I run into a similar issue a few days ago. The solution I found is to keep radius really small, around 70 meters. Then shift the search location lat-long left, right, up down until you cover all the necessary area of interest. If you mostly get 60 results with given conditions, that means your radius is still big for the area, make it smaller.

**Comment by NicolasBerger** [comment]
I actually want to get every place in a major city. 
So I have to call the method a tremendous amount of time with different latitude and longitude to cover the whole city.
With a small radius to try not to have two time the same place, then eventually I have to remove from the list the places that are already in it.
This is not very optimized and I guess some places would be missed.

**Comment by NicolasBerger** [comment]
Aw ok that's what I thought. It's a shame Google's API doesn't help us that way.

**Comment by hamdikavak** [comment]
Unfortunately, it does not help. Especially with 1000/day query limit, it can take weeks to cover the whole city.

**Comment by NicolasBerger** [comment]
Damn, and I thought I would be able to cover Paris within minutes, let's say hours if needed...

**Comment by hamdikavak** [comment]
I am pulling my hair since last week to cover a city that is way smaller and less populous than Paris. And still not there yet.

**Comment by NicolasBerger** [comment]
If it helps I just saw that you can have up to 150.000 request per 24h for free if you create a billing account that will not be used, only to check your identity.
It can make a difference on our applications.

**Comment by hamdikavak** [comment]
I saw that statement a while ago and I guess misunderstood what they say. You are right, you can get up to 100,000 requests for free.
