### ISSUE TITLE
Exceptions handling

### ISSUE THREAD

**Issue by NicolasBerger** [windy1/google-places-api-java#46]
Hi,

I'm having an issue with the exceptions caught by the API. My problem is that the API catches the exceptions and does not let me choose what to do when they occures.

My application is set to send 150k resquests a day (limited by Google) and write data in an excel file. But when an exception occures and is caught by the API my program just ends and I can't tell the application what to do next, and I'm afraid I will lose the data beacause I can't call ```HSSFWorkbook.write()``` from the Apache POI API.

Would it be possible not to catch some exceptions but to throw them so the developper can handle them ? Mostly those caught by the ```GooglePlace``` class.

**Comment by hamdikavak** [comment]
I guess all you have to do is to call the API methods within a try block
and do whatever you want to do within corresponding catch block when an
exception is thrown.
BTW, I would go with a database rather than excel.

**Comment by NicolasBerger** [comment]
I know the database seems to be a better option and it should be implemented in the future.
I cannot call the API methods within a try block, since it's handled directly inside the methods it is not thrown to the calling statement anymore. I could write a try/catch but it would never catch anything.

**Comment by hamdikavak** [comment]
It may help if you paste your code here. try-catch block perfectly works in my case.

**Comment by NicolasBerger** [comment]
Here's my code, with two calls to the API methods : ```getNearbyPlaces``` and ```getPlaceById```.
How did you catch the exceptons ?

```java
List<Place> list = client.getNearbyPlaces(pointRecherche.getX(), pointRecherche.getY(), DISTANCE_CALCUL, GooglePlaces.MAXIMUM_RESULTS);
for (Place place : list) {
	if(null == filteredTypes.stream().filter(s->place.getTypes().contains(s)).findFirst().orElse(null) && !places.contains(place.getPlaceId())){
		places.add(place.getPlaceId());
		fileWriter.writePlace(place.getPlaceId(), client.getPlaceById(place.getPlaceId(), new Param[0]));
	}
}
```

**Comment by hamdikavak** [comment]
My code is similar to your in some respect. I would write my code in the following way:

```java
List<Place> list = null;
Place tempPlace;

try{
    list = client.getNearbyPlaces(pointRecherche.getX(), pointRecherche.getY(), DISTANCE_CALCUL, GooglePlaces.MAXIMUM_RESULTS);
}
catch(GooglePlacesException ex){
    //handle exception here
}

for (Place place : list) {
    if(null == filteredTypes.stream().filter(s->place.getTypes().contains(s)).findFirst().orElse(null) && !places.contains(place.getPlaceId())){
        places.add(place.getPlaceId());
        try{
            tempPlace = client.getPlaceById(place.getPlaceId(), new Param[0])
            fileWriter.writePlace(place.getPlaceId(), tempPlace);
        }
        catch(GooglePlacesException ex){
              //handle exception here
        }
    }
}
```
You can implement more specific exception handling using the exception classes in here https://github.com/windy1/google-places-api-java/tree/master/src/main/java/se/walkercrou/places/exception

**Comment by NicolasBerger** [comment]
LMAO, I should get some sleep. I didn't even notice the catch statement throws another exception. Shouldn't ```throws GooglePlacesException``` be added to the method's signature so you are sure the exception will be caught by the calling method and you notify that an exception might be thrown ? 
In any case I added it to my GooglePlaces class wrapper so will know it next time lol.

**Comment by NicolasBerger** [comment]
While we in the exceptions, I had an issue with ```Place.parseDetails()``` method called by ```GooglePlaces.getPlaceById()```. If the result field is not present in the response, a NullPointerException is thrown. I call ```getPlaceById()``` with  IDs given by ```getNearbyPlaces()``` and I couldn't have any result with 3 or 4 of these IDs so my program just ends.
A null check would be helpful.

**Comment by hamdikavak** [comment]
I experienced that issue too. For some reason, either 1) Google does not provide details or  2) this library has some problems with parsing Ids for specific places. In my case, I had just 13 places like that out of 46k so I ignored them.

**Comment by NicolasBerger** [comment]
I had some questionnable results with the Hours as well. For some reason their API doesn't provide the opening/closing periods, but when i search the place on Google Chrome, Google displays the periods ...
