### ISSUE TITLE
getNearbyPlaces with rankby

### ISSUE THREAD

**Issue by faizandedia** [windy1/google-places-api-java#5]
Hey Thanks for the library!

Can you add the function to getNearbyPlaces with rankby. Right now is with radius. I want to show the results based on ranking. 

trying to create the subclass but due to buildUrl is private method unable to do that. I am using jar file

Thanks

**Comment by windy1** [comment]
@faizandedia @EpicDraws Implemented in 072e9eb4e26be47e0240afd16ea49eadf98e037e
